version: '3'

services:
  mongodb:
    image: mongo:4
    volumes:
      - './data/db:/data/db'
    networks:
      - easy-mock
    restart: always

  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
    volumes:
      - './data/redis:/data'
    networks:
      - easy-mock
    restart: always

  web:
    image: easy-test:1.0
    command: sh -c "npm start"
    ports:
      - 7300:7300
    volumes:
      - './logs:/app/logs'
      - './config/production.json:/app/config/production.json'
    networks:
      - easy-mock
    restart: always

networks:
  easy-mock:
